default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: sucodelaranja
  pool: 5

development:
  <<: *default
  database: arqueo_biblioteca_digital_development

test:
  <<: *default
  database: arqueo_biblioteca_digital_test

production:
  <<: *default
  database: arqueo_biblioteca_digital_production
